# JZG API Configuration
# (我使用了您 SignUtil.java 中的测试/沙箱环境地址和凭证)
jzg.api.base-url=http://nvapi.sandbox.jingzhengu.com
jzg.api.partner-id=1010
jzg.api.secret-key=Bg3pyUZrU6skS89m0URfFvNJ

# (可选) 指定服务端口
server.port=8080
